services:
  plexflixarr:
    image: ghcr.io/cmaguranis/plexflixarr:latest
    container_name: plexflixarr
    restart: unless-stopped
    ports:
      - 8742:8742
    environment:
      - TZ=${{ tz }}

      # Plex
      - PLEX_URL=http://192.168.1.67:32400
      - PLEX_TOKEN=

      # TMDB
      - TMDB_API_KEY=

      # TVDB
      - TVDB_API_KEY=

      # Simkl
      - SIMKL_CLIENT_ID=
      - SIMKL_FALLBACK_CLIENT_ID=

      # Simkl list names (used as DB keys and Plex collection names)
      # - SIMKL_LIST_NAME_KDRAMAS=K-Dramas
      # - SIMKL_LIST_NAME_KREALITY=Korean Reality
      # - SIMKL_LIST_NAME_REALITY=Reality TV
      # - SIMKL_LIST_NAME_TRENDING_TV=Trending TV
      # - SIMKL_LIST_NAME_TRENDING_MOVIES=Trending Movies
      # - SIMKL_LIST_NAME_TRENDING_ANIME=Trending Anime

      # Plex library section names
      # - DISCOVER_MOVIES_LIB=Movies
      # - DISCOVER_SHOWS_LIB=TV Shows
      # - REAL_LIBS=[]

      # Database path (must match volume mount below)
      - SIMKL_LISTS_DB_FILE=/data/simkl_lists.db
    volumes:
      - ${{ sf:"media" }}:/media:shared
      - ${{ sf:"appdata" }}/plexflixarr:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "7"
    cpu_shares: 256
