services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync
    environment:
      - PUID=0
      - PGID=0
      - TZ=${{ tz }}
    volumes:
      - ${{ sf:"appdata" }}/plextraktsync/config:/app/config
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "7"
    cpu_shares: 128